name: Frontend CI

on:
  push:
    branches: [ main, master, develop, developing, codex-1 ]
  pull_request:
    branches: [ main, master, develop ]

env:
  NODE_VERSION: '20.x'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        echo "✅ Dependencies installed"
    
    - name: Run type checking
      run: |
        npm run type-check
        echo "✅ TypeScript compilation successful"
    
    - name: Run linter
      run: |
        npm run lint
        echo "✅ ESLint check passed"
    
    - name: Check formatting
      run: |
        npx prettier --check "src/**/*.{ts,tsx,vue,js,jsx}"
        echo "✅ Code formatting check passed"
    
    - name: Run unit tests
      run: |
        npm run test:unit -- --coverage
        echo "✅ Unit tests passed"
    
    - name: Check coverage threshold
      run: |
        # Extract coverage percentage from the test output
        COVERAGE_FILE="coverage/coverage-summary.json"
        if [ -f "$COVERAGE_FILE" ]; then
          COVERAGE=$(node -e "const cov=require('./$COVERAGE_FILE'); console.log(cov.total.lines.pct)")
          echo "Total coverage: $COVERAGE%"
          
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "❌ Coverage $COVERAGE% is below 80% threshold"
            exit 1
          fi
          echo "✅ Coverage check passed"
        else
          echo "⚠️ Coverage file not found, skipping coverage check"
        fi
    
    - name: Build
      run: |
        npm run build
        echo "✅ Build successful"
        
        # Check bundle size
        BUNDLE_SIZE=$(du -sb dist/ | cut -f1)
        MAX_SIZE=2097152  # 2MB in bytes
        if [ $BUNDLE_SIZE -gt $MAX_SIZE ]; then
          echo "❌ Bundle size $(($BUNDLE_SIZE / 1024 / 1024))MB exceeds 2MB limit"
          exit 1
        fi
        echo "✅ Bundle size: $(($BUNDLE_SIZE / 1024 / 1024))MB"
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-dist
        path: dist/
        retention-days: 7
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/
        retention-days: 7